version: '3.3'

services:
  php:
    container_name: php
    build:
      context: ./.docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html
    environment:
      - NETTE_DEBUG=1
    user: appuser
    networks:
      nette:
        aliases:
          - php

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - '81:80'
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
      - adminer
      - composer
    networks:
      nette:
        aliases:
          - nginx

  database:
    container_name: database
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: nette
      MYSQL_USER: nette
      MYSQL_PASSWORD: nette
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - '4306:3306'
    volumes:
      - ./.mysql:/var/lib/mysql
    user: "1000:1000"
    networks:
      nette:
        aliases:
          - mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DATABASE: nette
      ADMINER_USER: nette
      ADMINER_PASSWORD: nette
      ADMINER_DESIGN: ng9
    depends_on:
      - database
    networks:
      nette:
        aliases:
          - adminer

  composer:
    image: composer:2
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    user: "1000:1000"
    depends_on:
      - php
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      nette:
        aliases:
          - composer

networks:
  nette:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

volumes:
  db-data:
    driver: local
